name = "pawlert-api"
main = "src/index.js"
compatibility_date = "2024-02-17"
workers_dev = true

routes = [
	{ pattern = "api.pawlert.co", custom_domain = true }
]

# [triggers]
# crons = [ "0 14 * * *", "0 19 * * *", "0 9 * * *" ]

[ai]
binding = "AI"
